echo -n "."
xsearch -db pubmed -query "(mIPSC|neurite|neurogenesis|neuroplasticity|plasticity|synaptic|5 ht|acetylcholine|cholinergic|DAergic|dopamine|dopaminergic|GABA|GABAergic|glutamate|glutamatergic|muscarinic|neuropeptides|neurotransmission|nicotinic|serotonergic|serotonin|glycosylation|phosphorylation|signaling|signalling|kinase|binding|signal transduction|second messengers|cGMP|cAMP|histone|hypermethylation|hypomethylation|methylation|ribosome|transcription|anxiety|anxious|autism|autistic|bipolar disorder|compulsive|obsessive) AND (Penk OR Rgma [tiab])" |xfetch -db pubmed > list5a.txt
echo -n "."
xsearch -db pubmed -query "(acbc|acbs|accumbal|accumbens|core|Nacc|NacSh|shell|amy|amygdala|bla|cea|cna|cerebral|cingulate|cortex|cortico limbic|corticolimbic|corticostriatal|infralimbic|insular|mPFC|orbitofrontal|pfc|prefrontal|prelimbic|prl|vmpfc|habenula|lhb|mhb|ca1|ca3|dentate gyrus|dhpc|hip|hipp|hippocampal|hippocampus|subiculum|vhipp|vhpc|hypothalamic|hypothalamus|LHA|paraventricular nucleus|PVN|basal ganglia|caudate|globus pallidus|GPI|putamen|STR|striatal|striatum|limbic|mesoaccumbal|mesoaccumbens|mesolimbic|midbrain|pvta|ventral tegmental|vta|addiction|addictive|compulsive|drug abuse|escalation|punishment|aversion|aversive|conditioned taste aversion|CTA|dependence|binge|intoxication|craving|drug seeking|reinstatement|relapse|seeking|conditioned place preference|CPP|drug reinforced|hedonic|ICSS|incentive|instrumental response|intracranial self stimulation|operant|reinforcement|reinforcing|reward|self administered|self administration|behavioral sensitization|locomotor sensitization|drug sensitization|incentive sensitization|social|withdrawal|acamprosate) AND (Penk OR Rgma [tiab])"|xfetch -db pubmed > list1.txt
echo -n "."
 xsearch -db pubmed -query "(alcohol|alcoholics|alcoholismoperant|reinforcement|reinforcing|reward|self administered|self administration|behavioral sensitization|drug sensitization|incentive sensitization|social|withdrawal|acamprosate|alcohol|alcoholics|alcoholism|antabuse|campral|disulfiram|ethanol|naltrexone|revia|vivitrol|AMPH|amphetamine|METH|methamphetamine|adinazolam|alprazolam|benzodiazepine|benzos|brotizolam|chlordiazepoxide|climazolam|clobazam|clonazepam|clorazepate|diazepam|estazolam|flunitrazepam|flurazepam|halazepam|librium|loprazolam|lorazepam|lormetazepam|midazolam|nimetazepam|nitrazepam|normison|oxazepam|prazepam|temazepam|triazolam|valium|xanax|acylethanolamines|cannabichromene|cannabidiol|cannabigerol|cannabinoids|cannabinol|cannabis|cannabivarin|cesamet|drobinal|dronabinol|endocannabinoids|epidiolex|JWH 018|JWH 122|JWH 250|marijuana|marinol|nabilone|Oleoylethanolamide|palmitoylethanolamide|phytocannabinoid|rimonabant|SR141716|SR144528|syndros|tetrahydrocannabinol|tetrahydrocannabivarin|thc|thc 9|cocaine|nicotine|smokers|smoking|tobacco)  AND (Penk OR Rgma [tiab])"|xfetch -db pubmed > list2.txt
echo -n "."
 xsearch -db pubmed -query "(buprenorphine|codeine|fentanyl|heroin|hycodan|hydrocodone|hydromorphone|kadian|kratom|methadone|morphine|naloxone|opioids|oxycodone|oxycontin|percocet|suboxone|tramadol|ultram|vicodin|ayahuasca|ecstasy|ibogaine|ketamine|LSD|lysergic acid diethylamide|MDMA|mescaline|methylenedioxymethamphetamine|N methoxybenzyl|NBOMes|peyote|psilocybin|psychedelic|psychedelics|boutons|epsc|epsp|IPSC|IPSP|long term depression|long term potentiation)  AND (Penk OR Rgma [tiab])"|xfetch -db pubmed > list2a.txt
echo -n "."
 xsearch -db pubmed -query  "(depressive|major depressive disorder|MDD|5 CSRTT|5 choice task|delay discounting|delay exposure|delay intolerance|delayed reward|delay task|five choice serial reaction time task|impulsive|impulsivity|premature responding|schizophrenia|adrenergic neurons|cholinergic neurons|dopaminergic neurons|gabaergic neurons|glutamatergic neurons|GnRH neurons|interneurons|monoaminergic neurons|medium spiny neurons|motor neurons|neuronal cells|nitrergic neurons|noradrenergic neurons|projection neurons|pyramidal neurons|sensory neurons|serotonergic neurons|somatostatin neurons|neurons|excitatory neurons|inhibitory neurons|corticospinal neurons|dopamine neurons|D1 neurons|D2 neurons|afferent neurons|efferent neurons|serotonin neurons|cortical neurons|hippocampal neurons|DA neurons|CNS neurons|cortex neurons|mesencephalic neurons|orexin neurons|catecholaminergic neurons|striatal neurons|bipolar neurons|ganglion cells|RGC|horizontal cells|amacrine cells|astrocytic|astrocytes|astroglia|astroglial|microglia|microglial|endothelium|endothelial cells|oligodendrocytes|PTSD|post traumatic stress)  AND (Penk OR Rgma [tiab])"|xfetch -db pubmed > list3.txt
echo -n "."
xsearch -db pubmed -query "(post traumatic stress symptoms|post traumatic stress disorder|distress|psychological trauma|stress|psychiatric|schizophrenia|autism|depression|anxiety|bipolar|mental|nicotine|smoking|chronic obstructive|tobacco|addiction|cocaine|opioid|morphine|amphetamine|methadone|heroin|drug dependence)  AND (Penk OR Rgma [tiab])"|xfetch -db pubmed > list4.txt
 # AND (Penk OR Rgma [tiab])"
# | xfetch -db pubmed
